services:

  # postgresql database
  db:
    image: postgres:latest
    ports:
      - "5332:5432"
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

